stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw/training.1600000.processed.noemoticon.csv
    - src/prepare.py
    outs:
    - data/processed/X_train.txt
    - data/processed/X_valid.txt
    - data/processed/train_neg.txt
    - data/processed/train_pos.txt
    - data/processed/val_neg.txt
    - data/processed/val_pos.txt
    - data/processed/vocab.json
    - data/processed/y_train.txt
    - data/processed/y_valid.txt
