# Generated by Django 4.0.6 on 2022-10-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(blank=True, null=True)),
                ('classified_model', models.BooleanField(null=True)),
                ('verified_user', models.BooleanField(null=True)),
            ],
        ),
    ]
